### ISSUE TITLE
Database connection error during Github CI/CD

### ISSUE THREAD

**Issue by 77media-creations** [Sammyjo20/Lasso#52]
Hello there,

I tried to compile assets during Github CI/CD. All my php unit tests run successfully but when it comes to compiling the assets using `php artisan lasso:publish` , it fails, see the error screenshot below.

It works on my localhost and successfully uploads the assets.

Looks like it cannot connect to the database, however php unit tests are passed in the same workflow and they do connect to the database.

Here is the part of workflow to lasso publish:
```
    - name: Compile & upload assets
        if: ${{ github.ref == 'refs/heads/production' && github.event_name == 'push' }}
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: php artisan lasso:publish --no-git
```

This is the error I get on github actions:

![Screen Shot 2021-10-31 at 10 04 03 am](https://user-images.githubusercontent.com/51688338/139560795-41b14c2e-db22-4b02-a138-8c49ae835644.png)
